### 안드로이드 테스트(application/x-www-form-urlencoded - key=value&key=value)
POST http://kosa2.iptime.org:50232/attendanceCheck
Content-Type: application/x-www-form-urlencoded

empno=220101&time=2022-06-27 18:01:00

### 로그인 테스트
POST http://localhost:8080/login
Content-Type: application/json

{
    "empno": "220101",
    "password": "1111"
}

### 출퇴근 테스트
POST http://localhost:8080/attendanceCheck
Content-Type: application/x-www-form-urlencoded

empno=220109&time=2022-07-01 14:00:00

### 그래프 조회용 테스트
POST http://localhost:8080/main
Content-Type: text/plain

220101

